### ISSUE TITLE
adplay and adended events are not fired for each ad in an adpod

### ISSUE THREAD

**Issue by owenbt** [philipwatson/videojsx-vast-plugin#32]
Hi,

I was excited to see your recent support for Adpods. In testing with an adpod with multiple ads, I've noticed that `adplay` and `adended` events do not fire for each ad in the pod. Here's what I'm observing

1st ad
`adplay` fires
`adended` fires

2nd, 3rd, etc. ads
`adplay` does not fire
`adended` does not fire (though "Ad ended" is printed in the console.)

Final ad
`adplay` does not fire
`adended` does not fire
`vast-done` fires

Ideally we'd want to track each `adplay` and `adended` event for each ad in the pod. Is it possible to add support for those events? Looking forward to using this plugin more. Thanks for your work on it.

**Comment by philipwatson** [comment]
Thanks @owenbt for your kind words. I'm glad you find it useful :-)
Do you mean the `adplay` and `adended` events don't trigger the event listeners in this plugin or in your code?

I suspect you may be on an old version because the plugin doesn't print "Ad ended" to the console anymore. Have you tried the latest master?

I did a quick test using the dev setup (via `npm start`).. these events are called at the right times to get the behaviour I wanted. For example, on `adended` I wanted to complete (and trigger VAST complete) and start the next ad in the pod.

**Comment by owenbt** [comment]
Thanks @philipwatson for the quick reply! You're right, somehow I was using an outdated version of the plugin. And yes, I meant that the VJS event listeners in my code were not being triggered. The reason is actually because I was using the VJS `one` instead of `on` event handlers. Changing those to `on` has resolved the issue.

One other thing I was curious about was whether the `adplay` event corresponds to the VAST start, or does it fire before the VAST wrapper chain is fully unwrapped? If it's the latter what would be the preferred way to trigger VAST start?

**Comment by owenbt** [comment]
@philipwatson not sure if you saw my follow up question? Did it make sense?

**Comment by philipwatson** [comment]
Hi @owenbt . Yes the latter would be the preferred way if I understood you correctly. To be sure, what do you mean by VAST start? I'm assuming you mean the ad's start tracking event?

The `adplay` is basically the HTMLMediaElement `play` event... but prefixed with `ad` to signal the video playing is an ad. It happens just before the ad's tracking event is triggered. Definitely not before the VAST wrapper chain is unwrapped :-) 

You got me thinking and looking at some docs. It looks like the plugin may need to emit some events, like `ads-pod-started`, `ads-allpods-completed`, `ads-request`, `ads-load` etc. Like Brightcove's player: https://player.support.brightcove.com/advertising/ad-events-and-ad-objects.html#events . Will you be interested in that?

**Comment by owenbt** [comment]
Hi @philipwatson, 

> To be sure, what do you mean by VAST start? I'm assuming you mean the ad's start tracking event?
Yes, exactly. The ad's start tracking event.

That's good to know about the `adplay` event. I'm familiar with the [MailOnline plugin events](https://github.com/MailOnline/videojs-vast-vpaid#vastadstart). That looks pretty comparable to the `vast.adstart` event there. 

Yeah, all those extra events would be useful. I'm curious if you already have any VPAID specific events? Thanks again for your help with this!

**Comment by owenbt** [comment]
Hey @philipwatson,

I’m noticing the plugin freezes frequently. I have an example where it plays test VASTs correctly. But when running with production ads I’m seeing this freezing behavior quite a bit.

And I’m noticing it specifically when VASTs with no ads are attempted to be played. The plugin fires the `adrseady` event and then just stops. There aren’t any errors fired and the content does not play. I’ve been able to play the same VASTs successfully in the [MailOnline plugi](https://github.com/MailOnline/videojs-vast-vpaid)n. When there’s no ad in the VAST that plugin will fire a VAST ad error and then play the content. Here’s an example of the MailOnline error: `[videojs-vast-vpaid] AD ERROR: VAST Error: on VASTClient.getVASTAd.validateVASTTree, no Ad in VAST tree `

I’ve created some reproduceable test cases. One for the freezing behavior and one for the successful ad play. Would you be interested in taking a look? Since it contains our ad server and prebid integration I’d prefer to send the urls over email. If that works for you could you email me at [remoter.gerbils.0v@icloud.com](mailto:remoter.gerbils.0v@icloud.com)?

Thanks!
Owen

**Comment by philipwatson** [comment]
Sure thing. Just sent an email ;)
