### ISSUE TITLE
videojsx does not support m3u8 streaming vast ads

### ISSUE THREAD

**Issue by flytian123** [philipwatson/videojsx-vast-plugin#33]
hi,videojsx is a very good videojs, thanks a lot

but videojsx does not support m3u8 streaming vast ads，Test vast urls：

https://go.xlivrdr.com/api/models/vast?campaignId=165aea9bcdd7aabac45f72d02f58fd24b8416bc57cfc540b1b4409ac823564af&campaignType=smartpop&creativeId=9f0c6d7632ec682312531731367e3a34426806be3f36a4dc0863150456668102&duration=00%3A00%3A30&iterationId=200911&masterSmartpopId=2683&memberId=ooc7r3l1Ns0ttU7qrqbp7aZXSudVLa6iV07qZXSuldK6iuymeiqV0rpXSumdK6V0rpXTOldK6ZznSupzp0j1D.5zpXSuldK6V0rpXSulcH2A&p1=4581400&ruleId=139&skipOffset=00&smartpopId=3564&sourceId=4810852&tag=girls%2Fchinese&userId=1f2ad638bb163e0f21b19d6cbbcd5805b56eb7b1ef21117b6157eaf2a11915c9&variationId=28325

**Comment by philipwatson** [comment]
Hi @flytian123 
Ok, looks like it doesn't stop the streaming ad after the duration specified in the VAST (30 seconds). Will fix it this week.

**Comment by philipwatson** [comment]
Hi @flytian123 
I made the change in a branch I'm currently working on. In `better-vpaid`. Does it fix the problem for you?

**Comment by flytian123** [comment]
What is the URL of better-vpaid? thank you

**Comment by flytian123** [comment]
I found it, thank you very much

**Comment by philipwatson** [comment]
I have merged `better-vpaid` into master. So will close.
