### ISSUE TITLE
undefined

### ISSUE THREAD

**Issue by antoniomiotto** [philipwatson/videojsx-vast-plugin#41]
I've been trying to fix this error for 5 hours now...  could please help me fix it?  :(

player.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'enabled')
    at new od (player.js:1:736960)
    at new <anonymous> (player.js:1:746581)
    at t.vast (player.js:1:434623)

**Comment by philipwatson** [comment]
Hi @antoniomiotto Looks like `progressControl` is undefined when the vast plugin loads. Unfortunately, I'm unable to reproduce the problem. Have you got any more info I can work with? What's your browser? Are you using other plugins? What does your setup (html) look like?

Actually, I can reproduce in one way (albeit a bad way):
```javascript
// ...
  var player = videojs('vid1');
  player.controlBar.progressControl = undefined;
// ...
```

To my understanding, you shouldn't do this. Should hide or disable using videojs api like this:

```javascript
player.controlBar.progressControl.hide();
```
or
```javascript
player.controlBar.progressControl.disable();
```

Again, any info will be appreciated.

**Comment by antoniomiotto** [comment]
it got it working thanks.
